import React, { useEffect, useMemo, useState } from 'react';
import { Activity, BarChart3, BellRing, BrainCircuit, RefreshCw, SlidersHorizontal, Star } from 'lucide-react';
import { carregarBriefing, carregarStatusR59, compararTimes, enviarFeedbackR59, explicarAnalise } from '../services/intelligenceR59.js';

const Box = ({ children }) => <section className="rounded-3xl border border-white/10 bg-[#0b1220] p-4">{children}</section>;
const teamName = (x) => x?.teams?.home?.name && x?.teams?.away?.name ? `${x.teams.home.name} × ${x.teams.away.name}` : 'Partida';

export default function IntelligenceR59Pro({ prefs, jogos = [], onOpen }) {
  const [section, setSection] = useState('briefing'); const [data, setData] = useState([]); const [status, setStatus] = useState(null);
  const [message, setMessage] = useState(''); const [compare, setCompare] = useState(null); const [explanation, setExplanation] = useState(null);
  const followedTeams = useMemo(() => (prefs?.seguidos || []).filter((x) => x.type === 'team').slice(0, 20), [prefs?.seguidos]);
  const watch = useMemo(() => jogos.filter((x) => followedTeams.some((t) => String(t.id) === String(x?.teams?.home?.id || x?.home_team_id) || String(t.id) === String(x?.teams?.away?.id || x?.away_team_id))).slice(0, 20), [jogos, followedTeams]);

  useEffect(() => { carregarStatusR59().then(setStatus).catch(() => setStatus({ football: false, gemini: false })); }, []);
  async function load() { setMessage('Carregando dados reais…'); try { const value = await carregarBriefing(followedTeams.map((x) => x.id)); setData(value.items || []); setMessage(value.items?.length ? '' : 'Nenhum jogo encontrado para seus favoritos hoje.'); } catch (e) { setMessage(e.message); } }
  useEffect(() => { if (section === 'briefing' && !data.length) void load(); }, [section]);
  async function runCompare() { if (followedTeams.length < 2) return setMessage('Siga pelo menos dois times para comparar.'); setMessage('Comparando…'); try { setCompare(await compararTimes({ a: followedTeams[0].id, b: followedTeams[1].id })); setMessage(''); } catch (e) { setMessage(e.message); } }
  async function explain(id) { setMessage('Analisando fatores…'); try { const value = await explicarAnalise(id); setExplanation(value.explanation); setMessage(''); } catch (e) { setMessage(e.message); } }
  async function feedback(rating) { try { await enviarFeedbackR59({ feature: section, rating }); setMessage('Obrigado pela avaliação.'); } catch (e) { setMessage(e.message); } }

  const tabs = [['briefing','Resumo diário',BrainCircuit],['watch','Ao vivo',Activity],['compare','Comparar',BarChart3],['filters','Filtros',SlidersHorizontal]];
  return <div className="space-y-4"><div className="flex gap-2 overflow-x-auto">{tabs.map(([id,label,Icon]) => <button key={id} onClick={() => setSection(id)} className={`flex shrink-0 items-center gap-2 rounded-xl px-3 py-2 text-[10px] font-black ${section === id ? 'bg-fuchsia-600' : 'bg-white/5 text-slate-400'}`}><Icon className="h-4 w-4"/>{label}</button>)}</div>
    <Box><div className="flex items-center justify-between"><div><p className="text-[9px] font-black uppercase tracking-widest text-fuchsia-300">R59 Inteligência e retenção</p><h2 className="mt-1 text-lg font-black">Dados conectados pelo servidor</h2></div><span className={`h-3 w-3 rounded-full ${status?.football ? 'bg-emerald-400' : 'bg-amber-400'}`}/></div><p className="mt-2 text-xs text-slate-400">{status?.football ? 'API esportiva configurada.' : 'Modo pronto: configure a chave esportiva no Render para ativar os dados.'}</p></Box>
    {message && <p className="rounded-xl bg-blue-500/10 p-3 text-xs text-blue-200">{message}</p>}
    {section === 'briefing' && <><button onClick={load} className="flex w-full items-center justify-center gap-2 rounded-xl bg-fuchsia-600 p-3 text-xs font-black"><RefreshCw className="h-4 w-4"/>Atualizar resumo diário</button>{data.map((x) => <Box key={x.fixture?.id}><p className="text-xs font-black">{teamName(x)}</p><p className="mt-1 text-[9px] text-slate-500">{x.league?.name} · {x.fixture?.date ? new Date(x.fixture.date).toLocaleString('pt-BR') : ''}</p><div className="mt-3 flex gap-2"><button onClick={() => onOpen?.(x)} className="rounded-xl bg-white/5 px-3 py-2 text-[10px] font-bold">Abrir jogo</button><button onClick={() => explain(x.fixture?.id)} className="rounded-xl bg-violet-600 px-3 py-2 text-[10px] font-bold">Explicar análise</button></div></Box>)}{explanation && <Box><h3 className="font-black">Por que esta análise?</h3><p className="mt-2 text-xs text-slate-300">{explanation.factors?.join(' · ') || 'O fornecedor não retornou fatores suficientes.'}</p><div className="mt-3 grid grid-cols-3 gap-2 text-center text-xs"><b>Casa {explanation.confidence?.home || '—'}</b><b>Empate {explanation.confidence?.draw || '—'}</b><b>Fora {explanation.confidence?.away || '—'}</b></div><p className="mt-3 text-[10px] text-amber-200">{explanation.limitations?.join(' ')}</p></Box>}</>}
    {section === 'watch' && <>{watch.length ? watch.map((x) => <button key={x.id || x.fixture?.id} onClick={() => onOpen?.(x)} className="w-full rounded-2xl bg-white/5 p-4 text-left text-xs font-black">{x.home_team || x.teams?.home?.name} × {x.away_team || x.teams?.away?.name}<span className="float-right text-emerald-300">Abrir</span></button>) : <Box><BellRing className="text-amber-300"/><p className="mt-2 text-xs text-slate-400">Siga times para montar sua central compacta ao vivo.</p></Box>}</>}
    {section === 'compare' && <><button onClick={runCompare} className="w-full rounded-xl bg-cyan-600 p-3 text-xs font-black">Comparar meus dois primeiros times</button>{compare && <Box><h3 className="font-black">Confronto e desempenho</h3><p className="mt-2 text-xs text-slate-400">{compare.head_to_head?.length || 0} confrontos recentes encontrados. Dados completos aparecem conforme a cobertura do plano da API.</p></Box>}</>}
    {section === 'filters' && <Box><h3 className="font-black">Filtros avançados</h3><p className="mt-2 text-xs text-slate-400">Use seus times seguidos, competição, data e status na busca existente. A R59 mantém filtros sem inventar dados ausentes.</p></Box>}
    <Box><p className="text-xs font-bold">Este recurso foi útil?</p><div className="mt-3 flex gap-2">{[1,2,3,4,5].map((n) => <button key={n} onClick={() => feedback(n)} aria-label={`${n} estrelas`} className="rounded-xl bg-white/5 p-2"><Star className="h-4 w-4 text-yellow-300"/></button>)}</div></Box>
  </div>;
}
